import { decimal, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), stripeCustomerId: varchar("stripeCustomerId", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const pets = mysqlTable("pets", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), name: varchar("name", { length: 120 }).notNull(), species: varchar("species", { length: 50 }).notNull(), breed: varchar("breed", { length: 120 }), size: varchar("size", { length: 40 }), birthDate: timestamp("birthDate"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const categories = mysqlTable("categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull(), slug: varchar("slug", { length: 140 }).notNull().unique(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const products = mysqlTable("products", { id: int("id").autoincrement().primaryKey(), categoryId: int("categoryId"), name: varchar("name", { length: 180 }).notNull(), slug: varchar("slug", { length: 200 }).notNull().unique(), description: text("description"), price: decimal("price", { precision: 10, scale: 2 }).notNull(), promoPrice: decimal("promoPrice", { precision: 10, scale: 2 }), stock: int("stock").default(0).notNull(), imageUrl: text("imageUrl"), brand: varchar("brand", { length: 100 }), active: int("active").default(1).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const orders = mysqlTable("orders", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), status: mysqlEnum("status", ["pending", "paid", "preparing", "out_for_delivery", "delivered", "cancelled"]).default("pending").notNull(), total: decimal("total", { precision: 10, scale: 2 }).notNull(), paymentMethod: varchar("paymentMethod", { length: 40 }), stripePaymentIntentId: varchar("stripePaymentIntentId", { length: 120 }), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const orderItems = mysqlTable("orderItems", { id: int("id").autoincrement().primaryKey(), orderId: int("orderId").notNull(), productId: int("productId"), productName: varchar("productName", { length: 180 }).notNull(), unitPrice: decimal("unitPrice", { precision: 10, scale: 2 }).notNull(), quantity: int("quantity").notNull() });
export const services = mysqlTable("services", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull(), durationMinutes: int("durationMinutes").notNull(), price: decimal("price", { precision: 10, scale: 2 }).notNull(), active: int("active").default(1).notNull() });
export const appointments = mysqlTable("appointments", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), petId: int("petId"), serviceId: int("serviceId").notNull(), startsAt: timestamp("startsAt").notNull(), status: mysqlEnum("status", ["requested", "confirmed", "in_service", "completed", "cancelled"]).default("requested").notNull(), transport: mysqlEnum("transport", ["store", "pickup"]).default("store").notNull(), pickupAddress: text("pickupAddress"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const siteSettings = mysqlTable("siteSettings", { id: int("id").autoincrement().primaryKey(), storeName: varchar("storeName", { length: 160 }).default("Power Pet").notNull(), logoUrl: text("logoUrl"), whatsapp: varchar("whatsapp", { length: 40 }), phone: varchar("phone", { length: 40 }), email: varchar("email", { length: 320 }), address: text("address"), openingHours: text("openingHours"), instagram: varchar("instagram", { length: 160 }), deliveryRegions: text("deliveryRegions"), deliveryFee: decimal("deliveryFee", { precision: 10, scale: 2 }).default("0.00").notNull(), paymentMode: mysqlEnum("paymentMode", ["manual", "stripe", "pix"]).default("manual").notNull(), stripeEnabled: int("stripeEnabled").default(0).notNull(), whatsappEnabled: int("whatsappEnabled").default(0).notNull(), serviceDuration: int("serviceDuration").default(60).notNull(), simultaneousCapacity: int("simultaneousCapacity").default(2).notNull(), blockedDates: text("blockedDates"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Product = typeof products.$inferSelect;
export type Appointment = typeof appointments.$inferSelect;
export type SiteSettings = typeof siteSettings.$inferSelect;
