import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function Profile() {
  const { user, loading, logout } = useAuth(); const utils = trpc.useUtils(); const [mode, setMode] = useState<"login" | "register">("login"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const login = trpc.auth.login.useMutation({ onSuccess: () => utils.auth.me.invalidate(), onError: e => toast.error(e.message) }); const register = trpc.auth.register.useMutation({ onSuccess: () => { toast.success("Conta criada."); utils.auth.me.invalidate(); }, onError: e => toast.error(e.message) }); const update = trpc.auth.profile.update.useMutation({ onSuccess: () => { toast.success("Perfil atualizado."); utils.auth.me.invalidate(); }, onError: e => toast.error(e.message) });
  if (loading) return <div className="grid min-h-screen place-items-center">Carregando...</div>;
  if (user) return <main className="mx-auto min-h-screen max-w-xl p-6 pt-16"><Link href="/" className="text-sm text-[#357367]">← Voltar para a loja</Link><h1 className="mt-6 text-3xl font-semibold">Meu perfil</h1><div className="mt-8 space-y-4 rounded-2xl border bg-white p-6"><Input value={name || user.name || ""} onChange={e => setName(e.target.value)} placeholder="Nome" /><Input value={email || user.email || ""} onChange={e => setEmail(e.target.value)} type="email" placeholder="E-mail" /><Input value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="Nova senha (opcional, mínimo 10 caracteres)" /><Button className="w-full" onClick={() => update.mutate({ name: name || undefined, email: email || undefined, password: password || undefined })} disabled={update.isPending}>Salvar perfil</Button>{user.role === "admin" && <Link href="/admin" className="block text-center text-sm text-[#357367]">Abrir painel administrativo</Link>}<Button variant="outline" className="w-full" onClick={() => logout()}>Sair</Button></div></main>;
  const submit = () => mode === "login" ? login.mutate({ email, password }) : register.mutate({ name, email, password });
  return <main className="mx-auto grid min-h-screen max-w-md place-items-center p-6"><div className="w-full rounded-2xl border bg-white p-6 shadow-sm"><Link href="/" className="text-sm text-[#357367]">← Voltar para a loja</Link><h1 className="mt-6 text-3xl font-semibold">{mode === "login" ? "Entrar" : "Criar conta"}</h1><div className="mt-6 space-y-3">{mode === "register" && <Input value={name} onChange={e => setName(e.target.value)} placeholder="Nome completo" />}<Input value={email} onChange={e => setEmail(e.target.value)} type="email" placeholder="E-mail" /><Input value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="Senha (mínimo 10 caracteres)" /><Button className="w-full" onClick={submit} disabled={!email || !password || (mode === "register" && !name) || login.isPending || register.isPending}>{mode === "login" ? "Entrar" : "Criar conta"}</Button><button className="w-full text-sm text-[#357367]" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "Ainda não tenho conta" : "Já tenho uma conta"}</button></div></div></main>;
}
